spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_123456?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #type: com.zaxxer.hikari.HikariDataSource
#  jdbc:
#    template:
#      query-timeout: 3 # 超时时间为3秒